defaults: &defaults
  docker_url: 'tcp://172.16.42.43:4243'
  platform_host: 'http://localhost:3000'
  base_image: <%= ENV['BASE_IMAGE'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  platform_host: <%= ENV['PLATFORM_HOST'] %>
  <<: *defaults
